name: webview
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  internet_connection_checker_plus: ^2.6.0
  permission_handler: ^11.3.1
  webview_flutter: ^4.10.0
  geolocator: ^13.0.2
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  flutter_image_compress: ^2.3.0
  logger: ^2.5.0
  file_picker: ^8.1.6
  screenshot: ^3.0.0
  share_plus: ^10.1.3
  device_info_plus: ^11.2.0
  package_info_plus: ^8.1.2
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  firebase_analytics: ^11.3.6
  flutter_udid: ^4.0.0     

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/


